version: '3'

services:
  api-with-model:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api-with-model
    ports:
      - 8000:8000
    healthcheck:
      test: 
        - CMD
        - curl -X POST http://localhost:8000/predict
        - -H
        - "Content-Type: application/json"
        - -d
        - '{"medinc:1, houseage:2, averooms:3, avebedrms:4, population:5, aveoccup:6, latitude:7, longitude:8"}'
      interval: 10s
      timeout: 5s
      retries: 5
    
networks:
  default:
    name: mlops-network
    external: true