global:
  scrape_interval: 15s #scraping 간격을 1분단위로 설정
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'ml-storage'
    static_configs:
      - targets: ['host.docker.internal:9001']
